### ISSUE TITLE
Wrong url in the plugin details.

### ISSUE THREAD

**Issue by MikiGrit** [taooceros/Flow.LibreTranslate#1]
When I installed the plugin and clicked on the "Website" link in the plugin details, it leads to "https://github.com/taooceros/Flow.Launcher.Plugin.LibreTranslate".

![Screenshot 2022-08-08 195332](https://user-images.githubusercontent.com/1949300/183482183-837c6f3e-8810-4494-85f2-34870d043c5c.png)

**Comment by taooceros** [comment]
Thanks
